# Production Supabase Configuration
# This file contains production-specific settings for Supabase

project_id = "university-job-bank-prod"

[api]
enabled = true
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
# Production site URL - update with your actual domain
site_url = "https://your-production-domain.vercel.app"
additional_redirect_urls = [
  "https://your-production-domain.vercel.app",
  "https://your-preview-domain.vercel.app"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
# Enable email confirmations in production for security
enable_confirmations = true

[auth.sms]
enable_signup = false
enable_confirmations = false

# Production SMTP configuration
[auth.email.smtp]
host = "smtp.resend.com"
port = 587
user = "resend"
# Use environment variable for password
pass = "env(SUPABASE_SMTP_PASSWORD)"
admin_email = "admin@acadiau.ca"
sender_name = "Acadia University Job Bank"

[edge_functions]
enabled = true