# Staging Supabase Configuration
# This file contains staging-specific settings for Supabase

project_id = "university-job-bank-staging"

[api]
enabled = true
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
# Staging site URL
site_url = "https://your-staging-domain.vercel.app"
additional_redirect_urls = [
  "https://your-staging-domain.vercel.app",
  "http://localhost:3000"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
# Disable email confirmations in staging for easier testing
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false

# Staging SMTP configuration (can use test SMTP)
[auth.email.smtp]
host = "smtp.mailtrap.io"
port = 587
user = "env(MAILTRAP_USER)"
pass = "env(MAILTRAP_PASSWORD)"
admin_email = "staging-admin@acadiau.ca"
sender_name = "Acadia Job Bank (Staging)"

[edge_functions]
enabled = true